//! Parallel Snapshot Engine — concurrent table-snapshot with PK-range chunking.
//!
//! # Architecture
//!
//! A **keeper** connection holds a `pg_export_snapshot()` for the entire
//! snapshot run.  N **worker** tasks (controlled by `num_workers`) compete
//! for chunks from a shared [`tokio::sync::mpsc`] work queue, each scanning
//! its assigned PK range via a server-side cursor.
//!
//! All workers pin their transactions to the same exported snapshot ID,
//! guaranteeing a globally consistent view.
//!
//! # Chunking
//!
//! Each table is divided into `num_workers × 2` chunks (over-subscription
//! for load balance).  Chunks are generated by querying `MIN(pk)/MAX(pk)`
//! and splitting the numeric range evenly.  Non-integer or composite PKs
//! fall back to a single chunk per table.
//!
//! # Resume
//!
//! On restart, the engine reads previously persisted chunk status from the
//! [`StateStore`].  `completed` chunks are skipped; `failed` and
//! `in_progress` chunks are re-issued.

use std::sync::Arc;
use std::time::{SystemTime, UNIX_EPOCH};

use tokio::sync::Mutex;
use tokio::sync::mpsc::{self, UnboundedSender};
use tracing::{error, info, warn};

use crate::config::{SnapshotConfig, SourceConfig};
use crate::error::TapError;
use crate::event::ChangeEvent;
use crate::postgres::{Lsn, connect_plain};
use crate::state::StateStore;

use super::chunker::{SnapshotChunk, generate_chunks, query_pk_range};
use super::runner::{
    SnapshotResult, TableInfo, detect_pk_columns, emit_row_event, parse_qualified_name,
    qualified_sql, quote_ident,
};

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Run a parallel, chunked snapshot of Postgres tables.
///
/// # Architecture
///
/// A persistent **run_id** (UUID v4) is generated at the start of each
/// snapshot run and stored in [`StateStore`] instance info.  After a crash,
/// the next invocation detects the stale run_id and resumes incomplete
/// chunks rather than starting from scratch.
///
/// The Postgres-level exported snapshot ID (from `pg_export_snapshot()`)
/// is kept separate — it changes every connection but does not affect chunk
/// tracking, which uses the persistent `run_id`.
///
/// # Arguments
///
/// * `keeper` — Connection that holds the exported snapshot for the full
///   duration.
/// * `source_config` — Postgres source config (used to spawn worker
///   connections and resolve publication tables).
/// * `state` — Shared state store for checkpointing chunk progress.
/// * `config` — Snapshot configuration (batch_size, num_workers, tables).
/// * `db_name` — Database name (for source metadata in events).
/// * `event_tx` — Channel for emitting `ChangeEvent`s.
///
/// # Errors
///
/// Propagates Postgres, SQLite, and snapshot-specific errors from any
/// worker or the keeper.  If a worker fails, the remaining workers are
/// allowed to finish their current chunk, then the error is returned.
///
/// # Example (conceptual)
///
/// ```rust,ignore
/// use tap_core::snapshot::parallel::run_parallel_snapshot;
///
/// let result = run_parallel_snapshot(
///     keeper, &source_config, state, &snap_config, "mydb", event_tx
/// ).await?;
/// ```
pub async fn run_parallel_snapshot(
    keeper: tokio_postgres::Client,
    source_config: &SourceConfig,
    state: Arc<Mutex<StateStore>>,
    config: &SnapshotConfig,
    db_name: String,
    event_tx: UnboundedSender<ChangeEvent>,
) -> Result<SnapshotResult, TapError> {
    // ── 0. Resolve persistent run_id (resume across restarts) ────
    let run_id = resolve_run_id(&state).await?;
    info!("snapshot run_id={run_id}");

    // ── 1. Begin keeper transaction & export snapshot ─────────────
    keeper
        .batch_execute("BEGIN READ ONLY ISOLATION LEVEL REPEATABLE READ")
        .await?;

    let export_result = export_snapshot_inner(&keeper).await;

    match export_result {
        Ok((pg_snapshot_id, lsn)) => {
            info!("pg_snapshot exported: id={pg_snapshot_id}, lsn={lsn}");

            let result = run_snapshot_inner(
                &keeper,
                source_config,
                &state,
                &run_id,
                &pg_snapshot_id,
                lsn,
                config.num_workers,
                config.batch_size as u32,
                &db_name,
                &event_tx,
            )
            .await;

            // Always close keeper
            keeper
                .batch_execute(match &result {
                    Ok(_) => "COMMIT",
                    Err(_) => "ROLLBACK",
                })
                .await
                .ok();

            result
        }
        Err(e) => {
            keeper.batch_execute("ROLLBACK").await.ok();
            Err(e)
        }
    }
}

// ---------------------------------------------------------------------------
// Resume detection
// ---------------------------------------------------------------------------

/// Resolve a persistent run-id for this snapshot run.
///
/// Checks the state store for a previously stored `current_run_id`.  If one
/// exists and has incomplete (non-completed) chunks, returns that id so the
/// caller resumes from where the previous run left off.  Otherwise generates
/// a fresh UUID and persists it.
async fn resolve_run_id(state: &Arc<Mutex<StateStore>>) -> Result<String, TapError> {
    let store = state.lock().await;
    let stored = store.get_instance_info("current_run_id")?;
    match stored {
        Some(id) if !id.is_empty() => {
            let incomplete = store.count_incomplete_chunks(&id)?;
            if incomplete > 0 {
                return Ok(id); // Resume mode
            }
            // Stale entry — all chunks completed or no chunks exist.
            // Overwrite with a fresh run_id.
            let new_id = uuid::Uuid::new_v4().to_string();
            store.set_instance_info("current_run_id", &new_id)?;
            Ok(new_id)
        }
        _ => {
            let new_id = uuid::Uuid::new_v4().to_string();
            store.set_instance_info("current_run_id", &new_id)?;
            Ok(new_id)
        }
    }
}

// ---------------------------------------------------------------------------
// Core orchestration
// ---------------------------------------------------------------------------

/// The inner snapshot loop (keeper transaction already active).
///
/// * `run_id` — Persistent chunk-grouping key (survives restarts for resume).
/// * `pg_snapshot_id` — Postgres export-snapshot ID for `SET TRANSACTION
///   SNAPSHOT` in worker connections.
#[allow(clippy::too_many_arguments)]
async fn run_snapshot_inner(
    keeper: &tokio_postgres::Client,
    source_config: &SourceConfig,
    state: &Arc<Mutex<StateStore>>,
    run_id: &str,
    pg_snapshot_id: &str,
    lsn: Lsn,
    num_workers: u32,
    batch_size: u32,
    db_name: &str,
    event_tx: &UnboundedSender<ChangeEvent>,
) -> Result<SnapshotResult, TapError> {
    // ── 2. Resolve tables (using keeper, since it has the tx) ────
    let tables = resolve_tables_inner(keeper, source_config).await?;
    if tables.is_empty() {
        info!("no tables to snapshot");
        return Ok(SnapshotResult {
            snapshot_id: run_id.to_string(),
            position: lsn,
            total_rows: 0,
            tables_snapshotted: Vec::new(),
        });
    }

    // ── 3. Generate chunks for each table ─────────────────────────
    let mut all_chunks: Vec<SnapshotChunk> = Vec::new();
    let mut tables_snapshotted: Vec<String> = Vec::with_capacity(tables.len());

    for table in &tables {
        let pk_cols = detect_pk_columns(keeper, table).await?;
        let pk_str = pk_cols.first().cloned().unwrap_or_default();

        // Load existing chunks for resume (keyed by persistent run_id)
        let existing = {
            let store = state.lock().await;
            store.get_table_chunks(run_id, &table.qualified)?
        };

        let chunks = if pk_str.is_empty() {
            // No PK — single chunk only
            let num_chunks = 1u32;
            generate_chunks(table, run_id, "", None, num_chunks, &existing)
        } else {
            let pk_range = query_pk_range(keeper, table, &pk_str).await?;
            let num_per_table = (num_workers * 2).max(1);
            generate_chunks(
                table,
                run_id,
                &pk_str,
                pk_range.as_ref(),
                num_per_table,
                &existing,
            )
        };

        // Register NEW chunks (skipped completed ones are not returned)
        {
            let store = state.lock().await;
            for chunk in &chunks {
                store.write_chunk(
                    &chunk.table_name,
                    &chunk.snapshot_id,
                    chunk.chunk_index,
                    chunk.chunk_start.as_deref(),
                    chunk.chunk_end.as_deref(),
                )?;
            }
        }

        // ── 3a. Detect chunk-size skew (pre-flight) ─────────────
        if chunks.len() > 1 && !pk_str.is_empty() {
            detect_chunk_skew(keeper, table, &pk_str, &chunks).await?;
        }

        all_chunks.extend(chunks);
        tables_snapshotted.push(format!("\"{}\".\"{}\"", table.schema, table.name));
    }

    if all_chunks.is_empty() {
        info!("all chunks already completed (resume)");
        // Reconstruct result from state store
        let total_rows = {
            let store = state.lock().await;
            store.snapshot_chunk_total_rows(run_id)?
        };
        return Ok(SnapshotResult {
            snapshot_id: run_id.to_string(),
            position: lsn,
            total_rows,
            tables_snapshotted,
        });
    }

    info!(
        total_chunks = all_chunks.len(),
        workers = num_workers,
        "starting parallel snapshot"
    );

    // ── 4. Distribute chunks via mpsc channel ────────────────────
    let num_chunks = all_chunks.len() as u32;
    let (work_tx, work_rx) = mpsc::channel::<SnapshotChunk>(num_chunks as usize);
    let work_rx = Arc::new(Mutex::new(work_rx));

    for chunk in all_chunks {
        work_tx
            .send(chunk)
            .await
            .map_err(|_| TapError::Snapshot("failed to enqueue chunk into work queue".into()))?;
    }
    // Drop the sender so receivers see None when all chunks are consumed
    drop(work_tx);

    // ── 5. Spawn worker tasks ────────────────────────────────────
    let mut handles = Vec::with_capacity(num_workers as usize);
    let error_flag = Arc::new(std::sync::atomic::AtomicBool::new(false));

    for worker_id in 0..num_workers {
        let work_rx = Arc::clone(&work_rx);
        let state = Arc::clone(state);
        let event_tx = event_tx.clone();
        let r_id = run_id.to_string();
        let pg_id = pg_snapshot_id.to_string();
        let db_name = db_name.to_string();
        let error_flag = Arc::clone(&error_flag);
        let source_config = source_config.clone();

        let handle = tokio::spawn(async move {
            worker_main(
                worker_id,
                source_config,
                work_rx,
                state,
                &r_id,
                &pg_id,
                lsn,
                batch_size,
                &db_name,
                event_tx,
                error_flag,
            )
            .await
        });

        handles.push(handle);
    }

    // ── 6. Wait for all workers to complete ──────────────────────
    let mut worker_errors: Vec<TapError> = Vec::new();

    for handle in handles {
        match handle.await {
            Ok(Ok(())) => {} // worker finished successfully
            Ok(Err(e)) => {
                error!("worker failed: {e}");
                worker_errors.push(e);
            }
            Err(join_err) => {
                error!("worker task panicked: {join_err}");
                worker_errors.push(TapError::Snapshot(format!(
                    "worker task panicked: {join_err}"
                )));
            }
        }
    }

    if !worker_errors.is_empty() {
        return Err(TapError::Snapshot(format!(
            "{} worker(s) failed: {:?}",
            worker_errors.len(),
            worker_errors
        )));
    }

    // ── 7. Compute final result ──────────────────────────────────
    let total_rows = {
        let store = state.lock().await;
        store.snapshot_chunk_total_rows(run_id)?
    };

    info!(
        run_id = %run_id,
        lsn = %lsn,
        total_rows,
        tables = %tables_snapshotted.len(),
        "parallel snapshot complete"
    );

    Ok(SnapshotResult {
        snapshot_id: run_id.to_string(),
        position: lsn,
        total_rows,
        tables_snapshotted,
    })
}

// ---------------------------------------------------------------------------
// Keeper: export snapshot
// ---------------------------------------------------------------------------

/// Export a Postgres snapshot and capture the WAL position.
async fn export_snapshot_inner(keeper: &tokio_postgres::Client) -> Result<(String, Lsn), TapError> {
    let snap_row = keeper.query_one("SELECT pg_export_snapshot()", &[]).await?;
    let snapshot_id: String = snap_row.get(0);

    let lsn_row = keeper
        .query_one("SELECT pg_current_wal_lsn()::text", &[])
        .await?;
    let lsn_str: String = lsn_row.get(0);
    let lsn: Lsn = lsn_str.parse()?;

    Ok((snapshot_id, lsn))
}

// ---------------------------------------------------------------------------
// Table resolution
// ---------------------------------------------------------------------------

/// Resolve tables from config or publication.
async fn resolve_tables_inner(
    keeper: &tokio_postgres::Client,
    source_config: &SourceConfig,
) -> Result<Vec<TableInfo>, TapError> {
    if !source_config.tables.is_empty() {
        let mut tables: Vec<TableInfo> = source_config
            .tables
            .iter()
            .map(|t| parse_qualified_name(t))
            .collect();
        tables.sort_by(|a, b| a.qualified.cmp(&b.qualified));
        return Ok(tables);
    }

    let pub_name = keeper
        .query_one(
            "SELECT COALESCE(pubname, 'tap_publication') FROM pg_publication LIMIT 1",
            &[],
        )
        .await
        .map(|r| {
            let s: String = r.get(0);
            s
        })
        .unwrap_or_else(|_| "tap_publication".into());

    let rows = keeper
        .query(
            "SELECT schemaname, tablename \
             FROM pg_publication_tables \
             WHERE pubname = $1 \
             ORDER BY schemaname, tablename",
            &[&pub_name],
        )
        .await?;

    if rows.is_empty() {
        warn!(
            publication = %pub_name,
            "publication has no tables — snapshot will be a no-op"
        );
    }

    let tables: Vec<TableInfo> = rows
        .iter()
        .map(|row| {
            let schema: String = row.get(0);
            let name: String = row.get(1);
            TableInfo {
                qualified: format!("{schema}.{name}"),
                schema,
                name,
            }
        })
        .collect();

    Ok(tables)
}

// ---------------------------------------------------------------------------
// Chunk skew detection (pre-flight)
// ---------------------------------------------------------------------------

/// Warn if chunk sizes are highly skewed (stddev > 2× mean).
///
/// Skew indicates the PK distribution is non-uniform, which commonly
/// happens with time-ordered UUIDs (`gen_random_uuid()` v1/v4) or
/// clustered integer keys.  In extreme cases a single worker ends up
/// scanning most of the rows while others sit idle.
async fn detect_chunk_skew(
    keeper: &tokio_postgres::Client,
    table: &TableInfo,
    pk_column: &str,
    chunks: &[SnapshotChunk],
) -> Result<(), TapError> {
    let sql_table = qualified_sql(table);
    let mut sizes = Vec::with_capacity(chunks.len());

    for chunk in chunks {
        let (clause, _, _) = chunk.where_clause(pk_column);
        let query = format!("SELECT COUNT(*) FROM {sql_table} {clause}");
        let row = keeper.query_one(&query, &[]).await.map_err(|e| {
            TapError::Snapshot(format!(
                "skew count query failed for {}: {e}",
                table.qualified
            ))
        })?;
        let count: i64 = row.get(0);
        sizes.push(count);
    }

    let n = sizes.len() as f64;
    if n <= 1.0 {
        return Ok(());
    }

    let total: i64 = sizes.iter().sum();
    let mean = total as f64 / n;

    if mean <= 0.0 {
        return Ok(());
    }

    // Population standard deviation
    let variance = sizes
        .iter()
        .map(|s| (*s as f64 - mean).powi(2))
        .sum::<f64>()
        / n;
    let stddev = variance.sqrt();

    if stddev > 2.0 * mean {
        warn!(
            table = %table.qualified,
            chunks = chunks.len(),
            stddev = %format!("{:.1}", stddev),
            mean = %format!("{:.0}", mean),
            "chunk size skew detected — stddev > 2× mean; PK may be non-monotonic"
        );
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Worker task
// ---------------------------------------------------------------------------

/// Main loop for a single worker task.
///
/// 1. Opens a plain connection to Postgres.
/// 2. Pins a REPEATABLE READ transaction to the exported snapshot.
/// 3. Loops: pops a chunk from the shared work queue → scans it → records
///    progress → marks chunk complete.
///
/// * `run_id` — Persistent chunk-grouping key (for state store operations).
/// * `pg_snapshot_id` — Postgres export-snapshot ID (for `SET TRANSACTION
///   SNAPSHOT`).
#[allow(clippy::too_many_arguments)]
async fn worker_main(
    worker_id: u32,
    source_config: SourceConfig,
    work_rx: Arc<Mutex<mpsc::Receiver<SnapshotChunk>>>,
    state: Arc<Mutex<StateStore>>,
    run_id: &str,
    pg_snapshot_id: &str,
    lsn: Lsn,
    batch_size: u32,
    db_name: &str,
    event_tx: UnboundedSender<ChangeEvent>,
    error_flag: Arc<std::sync::atomic::AtomicBool>,
) -> Result<(), TapError> {
    info!(worker_id, "worker starting");

    // ── Open worker connection ───────────────────────────────────
    let (mut client, handle) = connect_plain(&source_config).await?;

    // Run the worker loop
    let result = worker_loop(
        &mut client,
        worker_id,
        work_rx,
        state,
        run_id,
        pg_snapshot_id,
        lsn,
        batch_size,
        db_name,
        &event_tx,
        error_flag,
    )
    .await;

    // Drop client before awaiting the handle to avoid deadlock
    drop(client);
    handle.await.ok();

    result
}

/// Inner loop: claim chunks, scan, record progress.
///
/// * `run_id` — Persistent chunk-grouping key (for state store operations).
/// * `pg_snapshot_id` — Postgres export-snapshot ID for `SET TRANSACTION
///   SNAPSHOT`.
#[allow(clippy::too_many_arguments)]
async fn worker_loop(
    client: &mut tokio_postgres::Client,
    worker_id: u32,
    work_rx: Arc<Mutex<mpsc::Receiver<SnapshotChunk>>>,
    state: Arc<Mutex<StateStore>>,
    run_id: &str,
    pg_snapshot_id: &str,
    lsn: Lsn,
    batch_size: u32,
    db_name: &str,
    event_tx: &UnboundedSender<ChangeEvent>,
    error_flag: Arc<std::sync::atomic::AtomicBool>,
) -> Result<(), TapError> {
    // Start a REPEATABLE READ transaction pinned to the exported snapshot
    let txn = client.transaction().await?;
    txn.batch_execute("SET TRANSACTION ISOLATION LEVEL REPEATABLE READ")
        .await?;
    txn.simple_query(&format!("SET TRANSACTION SNAPSHOT '{pg_snapshot_id}'"))
        .await?;

    let ts_ms = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0);

    loop {
        // Check if another worker already failed
        if error_flag.load(std::sync::atomic::Ordering::Relaxed) {
            info!(worker_id, "shutting down due to sibling failure");
            break;
        }

        // Pop a chunk from the shared work queue
        let chunk: SnapshotChunk = {
            let mut rx = work_rx.lock().await;
            match rx.recv().await {
                Some(c) => {
                    // Mark in_progress immediately while holding the lock
                    // so no other worker claims it.
                    c
                }
                None => {
                    info!(worker_id, "no more chunks — done");
                    break;
                }
            }
        };

        // Mark in_progress in state store
        {
            let store = state.lock().await;
            store.start_chunk(run_id, &chunk.table_name, chunk.chunk_index)?;
        }

        // ── Detect PK for this table ─────────────────────────────
        let table = parse_qualified_name(&chunk.table_name);
        let pk_cols = detect_pk_columns(txn.client(), &table).await?;

        // ── Scan the chunk ───────────────────────────────────────
        let result = scan_chunk(
            txn.client(),
            &table,
            &pk_cols,
            &chunk,
            batch_size,
            ts_ms,
            &lsn,
            db_name,
            event_tx,
        )
        .await;

        match result {
            Ok(rows_count) => {
                // Mark chunk completed
                {
                    let store = state.lock().await;
                    store.complete_chunk(
                        run_id,
                        &chunk.table_name,
                        chunk.chunk_index,
                        rows_count,
                    )?;
                }
                info!(
                    worker_id,
                    table = %chunk.table_name,
                    chunk = chunk.chunk_index,
                    rows_count,
                    "chunk completed"
                );
            }
            Err(e) => {
                error!(
                    worker_id,
                    table = %chunk.table_name,
                    chunk = chunk.chunk_index,
                    error = %e,
                    "chunk failed"
                );
                // Record failure and set error flag
                {
                    let store = state.lock().await;
                    store.fail_chunk(
                        run_id,
                        &chunk.table_name,
                        chunk.chunk_index,
                        &e.to_string(),
                    )?;
                }
                error_flag.store(true, std::sync::atomic::Ordering::Relaxed);
                return Err(e);
            }
        }
    }

    txn.commit().await?;
    Ok(())
}

// ---------------------------------------------------------------------------
// Chunk scanner
// ---------------------------------------------------------------------------

/// Scan a single PK-range chunk using a server-side cursor.
///
/// Emits one `ChangeEvent` (op: Read) per row and returns the total row
/// count for the chunk.
#[allow(clippy::too_many_arguments)]
async fn scan_chunk(
    client: &tokio_postgres::Client,
    table: &TableInfo,
    pk_columns: &[String],
    chunk: &SnapshotChunk,
    batch_size: u32,
    ts_ms: u64,
    snapshot_lsn: &Lsn,
    db_name: &str,
    event_tx: &UnboundedSender<ChangeEvent>,
) -> Result<u64, TapError> {
    let sql_table = qualified_sql(table);
    let order_clause = if pk_columns.is_empty() {
        "ctid".to_string()
    } else {
        pk_columns
            .iter()
            .map(|c| quote_ident(c))
            .collect::<Vec<_>>()
            .join(", ")
    };

    // Build WHERE clause from chunk bounds
    let where_clause = if let Some(pk_col) = pk_columns.first() {
        let (clause, _, _) = chunk.where_clause(pk_col);
        if clause.is_empty() {
            String::new()
        } else {
            format!("WHERE {}", clause.trim_start_matches("WHERE "))
        }
    } else {
        String::new()
    };

    let query = format!("SELECT * FROM {sql_table} {where_clause} ORDER BY {order_clause}, ctid");

    // Declare cursor
    client
        .batch_execute(&format!("DECLARE chunk_cursor CURSOR FOR {query}"))
        .await?;

    let mut rows_done: u64 = 0;

    // Fetch loop
    loop {
        let fetch_sql = format!("FETCH FORWARD {} FROM chunk_cursor", batch_size);
        let batch = client.query(&fetch_sql, &[]).await?;

        if batch.is_empty() {
            break;
        }

        for row in &batch {
            emit_row_event(
                event_tx,
                table,
                pk_columns,
                snapshot_lsn,
                ts_ms,
                db_name,
                row,
            )?;
        }

        rows_done += batch.len() as u64;
    }

    // Cleanup cursor
    client.batch_execute("CLOSE chunk_cursor").await?;

    Ok(rows_done)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // ── SnapshotResult creation (sanity) ──────────────────────────

    #[test]
    fn test_parallel_result_creation() {
        let lsn = Lsn::from_u64(0x16B37428);
        let result = SnapshotResult {
            snapshot_id: "00000004-000004D8-1".into(),
            position: lsn,
            total_rows: 1000,
            tables_snapshotted: vec!["public.users".into(), "public.orders".into()],
        };

        assert_eq!(result.total_rows, 1000);
        assert_eq!(result.tables_snapshotted.len(), 2);
    }

    // ── Chunk WHERE clause integration ────────────────────────────

    #[test]
    fn test_chunk_where_integration() {
        let chunk = SnapshotChunk::new(
            "public.users".into(),
            "snap_1".into(),
            0,
            Some("1".into()),
            Some("26".into()),
        );
        let (clause, start, end) = chunk.where_clause("id");
        assert!(clause.contains(r#""id" >= 1"#), "clause={clause}");
        assert!(clause.contains(r#""id" < 26"#), "clause={clause}");
        assert_eq!(start, Some("1".into()));
        assert_eq!(end, Some("26".into()));
    }

    #[test]
    fn test_chunk_where_no_bounds() {
        let chunk = SnapshotChunk::new("public.empty".into(), "snap_2".into(), 0, None, None);
        let (clause, _, _) = chunk.where_clause("id");
        assert_eq!(clause, "");
    }

    // ── scan_chunk SQL generation (unit) ──────────────────────────

    #[test]
    fn test_scan_query_structure() {
        let chunk = SnapshotChunk::new(
            "public.users".into(),
            "snap_1".into(),
            0,
            Some("1".into()),
            Some("1001".into()),
        );
        let table = parse_qualified_name("public.users");
        let pk_cols = vec!["id".to_string()];

        let pk_col = pk_cols.first().unwrap();
        let (clause, _, _) = chunk.where_clause(pk_col);

        let sql_table = qualified_sql(&table);
        let order_clause = pk_cols
            .iter()
            .map(|c| quote_ident(c))
            .collect::<Vec<_>>()
            .join(", ");

        let query =
            format!("SELECT * FROM {sql_table} WHERE {clause} ORDER BY {order_clause}, ctid");

        assert!(query.contains("SELECT * FROM \"public\".\"users\""));
        assert!(query.contains(r#""id" >= 1"#), "query={query}");
        assert!(query.contains(r#""id" < 1001"#), "query={query}");
        assert!(query.contains("ORDER BY \"id\", ctid"));
    }
}
