/**
 * @tap/sdk — PostgreSQL Change Data Capture SDK
 *
 * Provides a native Node.js binding to the Tap CDC engine via napi-rs.
 */

// This file will be auto-generated by `napi build` in production.
// The placeholder below is for development / type-checking only.

/** Returns the Tap SDK version string. */
export function hello(): string {
  throw new Error(
    "Native module not loaded. Run `pnpm run build` first.",
  );
}
