//! `tap init` — scaffold a new Tap capture project.
//!
//! Creates the `.tap/` directory structure, writes a TOML config,
//! connects to Postgres to validate credentials and set up the
//! replication slot + publication, then generates TypeScript type
//! definitions for the captured tables.

use clap::Args;
use tap_core::config::SourceConfig;
use tap_core::error::TapError;
use tap_core::postgres::{PgConnection, connect_plain};

use crate::commands::inspect::generate_typescript_types;

/// Arguments for the `tap init` command.
#[derive(Args, Debug, Clone)]
pub struct InitArgs {
    /// Optional project name (for display purposes).
    pub name: Option<String>,

    /// Postgres database name to capture.
    #[arg(short = 'd', long = "db", required = true)]
    pub db: String,

    /// Replication slot name.
    #[arg(short = 's', long = "slot", default_value = "tap_slot")]
    pub slot: String,

    /// Publication name.
    #[arg(short = 'p', long = "publication", default_value = "tap_publication")]
    pub publication: String,

    /// Tables to capture (can be specified multiple times, e.g. `--table public.users`).
    #[arg(short = 't', long = "table")]
    pub tables: Vec<String>,

    /// Output directory for generated files.
    #[arg(short = 'o', long = "output", default_value = ".")]
    pub output: String,

    /// Replication plugin (`pgoutput` or `wal2json`).
    #[arg(long = "plugin", default_value = "pgoutput")]
    pub plugin: String,

    /// Overwrite existing configuration files without prompting.
    #[arg(short = 'f', long = "force")]
    pub force: bool,

    /// Postgres user for replication.
    #[arg(long = "user", default_value = "postgres")]
    pub user: String,

    /// Postgres password.
    #[arg(long = "password", default_value = "")]
    pub password: String,

    /// Postgres hostname.
    #[arg(long = "host", default_value = "localhost")]
    pub host: String,

    /// Postgres port.
    #[arg(long = "port", default_value_t = 5432)]
    pub port: u16,
}

/// Content for the `.tap/.gitignore` file.
const GITIGNORE_CONTENT: &str = "\
# Tap state files
state.db
state.db.bak
*.db
*.db.bak

# Local overrides
config.local.toml
";

/// Content for the `.tap/tap.ts` boilerplate.
const TAP_TS_BOILERPLATE: &str = r#"// Auto-generated by `tap init`
// Tap TypeScript client — subscribe to change events via SSE.

export interface TapEvent {
  event_type: "change" | "heartbeat" | "snapshot_start"
    | "snapshot_progress" | "snapshot_complete"
    | "streaming_start" | "error" | "shutdown";
  data: unknown;
  id?: string;
}

/**
 * Create an EventSource connection to the Tap SSE stream.
 */
export function connectTap(url: string): EventSource {
  const es = new EventSource(url);
  return es;
}

export type Operation = "c" | "u" | "d" | "r";

export interface SourceMetadata {
  db: string;
  schema: string;
  table: string;
  lsn: string;
  txId: string;
  tsMs: number;
  snapshot?: boolean;
}

export interface ChangeEvent {
  op: Operation;
  before: Record<string, unknown> | null;
  after: Record<string, unknown> | null;
  source: SourceMetadata;
  tsMs: number;
  id: string;
}
"#;

/// Run `tap init`.
pub async fn run(args: InitArgs) -> Result<(), TapError> {
    let tap_dir = format!("{}/.tap", args.output);
    let types_dir = format!("{tap_dir}/types");
    let fixtures_dir = format!("{tap_dir}/fixtures");

    // ── 1. Create directory structure ────────────────────────────────
    std::fs::create_dir_all(&tap_dir)?;
    std::fs::create_dir_all(&types_dir)?;
    std::fs::create_dir_all(&fixtures_dir)?;

    println!("✓ Created .tap/ directory structure");

    // ── 2. Write config.toml ──────────────────────────────────────────
    let config = crate::config::config_from_init_args(&args);
    let config_path = format!("{tap_dir}/config.toml");
    let config_toml = toml::to_string_pretty(&config)
        .map_err(|e| TapError::Config(format!("Failed to serialize config: {e}")))?;

    if std::path::Path::new(&config_path).exists() && !args.force {
        return Err(TapError::Config(format!(
            "{config_path} already exists. Use --force to overwrite."
        )));
    }
    std::fs::write(&config_path, &config_toml)?;
    println!("✓ Wrote {config_path}");

    // ── 3. Connect to Postgres (validate credentials) ────────────────
    let source = SourceConfig {
        host: args.host.clone(),
        port: args.port,
        dbname: args.db.clone(),
        user: args.user.clone(),
        password: args.password.clone(),
        slot_name: args.slot.clone(),
        publication: args.publication.clone(),
        tables: args.tables.clone(),
        plugin: args.plugin.clone(),
        ssl_mode: Default::default(),
    };

    let pg = PgConnection::connect(&source).await?;
    println!("✓ Connected to Postgres at {}:{}", source.host, source.port);

    // ── 4. Ensure replication slot + publication ─────────────────────
    let lsn = pg.ensure_replication_slot().await?;
    println!("✓ Replication slot '{}' ready (LSN {lsn})", args.slot);

    pg.ensure_publication().await?;
    println!("✓ Publication '{}' ready", args.publication);

    // Validate that configured tables exist
    if !args.tables.is_empty() {
        pg.validate_tables().await?;
        println!("✓ All configured tables exist");
    }

    // Close the replication connection
    pg.close().await;

    // ── 5. Generate TypeScript type definitions ──────────────────────
    if !args.tables.is_empty() {
        let (client, _handle) = connect_plain(&source).await?;
        let ts_types = generate_typescript_types(&client, &args.tables).await?;

        let ts_path = format!("{types_dir}/schema.d.ts");
        std::fs::write(&ts_path, &ts_types)?;
        println!("✓ Wrote type definitions to {ts_path}");
    }

    // ── 6. Write tap.ts boilerplate ──────────────────────────────────
    let tap_ts_path = format!("{tap_dir}/tap.ts");
    // Only write if it doesn't exist, or if --force is set
    if !std::path::Path::new(&tap_ts_path).exists() || args.force {
        std::fs::write(&tap_ts_path, TAP_TS_BOILERPLATE)?;
    }
    println!("✓ Wrote {tap_ts_path}");

    // ── 7. Write .gitignore ──────────────────────────────────────────
    let gitignore_path = format!("{tap_dir}/.gitignore");
    if !std::path::Path::new(&gitignore_path).exists() || args.force {
        std::fs::write(&gitignore_path, GITIGNORE_CONTENT)?;
    }
    println!("✓ Wrote {gitignore_path}");

    // ── 8. Print success summary ────────────────────────────────────
    println!();
    println!("✅ Tap project initialized in {tap_dir}");
    println!("   Config:  {config_path}");
    println!("   Slot:    {}", args.slot);
    println!("   Pub:     {}", args.publication);
    println!();
    println!("   Next step: run `tap capture` to start streaming changes.");

    Ok(())
}
