//! `tap inspect` — inspect database schema and generate type definitions.
//!
//! Connects to Postgres, queries `information_schema.columns` for the
//! configured tables, and emits TypeScript type definitions or JSON schema.

use std::collections::BTreeMap;
use std::fmt::Write as FmtWrite;

use clap::Args;
use tap_core::error::TapError;

/// Arguments for the `tap inspect` command.
#[derive(Args, Debug, Clone)]
pub struct InspectArgs {
    /// Path to the TOML configuration file.
    #[arg(
        short = 'c',
        long = "config",
        default_value_t = String::from(crate::config::DEFAULT_CONFIG_PATH)
    )]
    pub config: String,

    /// Output as JSON schema instead of TypeScript type definitions.
    #[arg(short = 'j', long = "json")]
    pub json: bool,

    /// Output file path.  Defaults to `.tap/types/schema.d.ts` (or
    /// `.tap/types/schema.json` with `--json`).  Use `-` for stdout.
    #[arg(short = 'o', long = "output")]
    pub output: Option<String>,
}

/// A single column descriptor returned from the information_schema query.
#[derive(Debug, Clone)]
pub(crate) struct ColumnInfo {
    pub column_name: String,
    pub data_type: String,
    pub is_nullable: bool,
}

/// Map a Postgres data type name to a TypeScript type string.
fn pg_type_to_ts(pg_type: &str) -> &'static str {
    match pg_type {
        "integer" | "int" | "int4" | "smallint" | "int2" | "bigint" | "int8" | "smallserial"
        | "serial" | "bigserial" | "serial8" | "real" | "float4" | "double precision"
        | "float8" | "numeric" | "decimal" | "money" | "oid" => "number",

        "boolean" | "bool" => "boolean",

        "character varying"
        | "varchar"
        | "character"
        | "char"
        | "text"
        | "citext"
        | "name"
        | "bpchar"
        | "timestamp"
        | "timestamptz"
        | "timestamp with time zone"
        | "timestamp without time zone"
        | "date"
        | "time"
        | "timetz"
        | "time with time zone"
        | "time without time zone"
        | "interval"
        | "uuid"
        | "bytea"
        | "inet"
        | "cidr"
        | "macaddr"
        | "macaddr8"
        | "point"
        | "line"
        | "lseg"
        | "box"
        | "path"
        | "polygon"
        | "circle"
        | "xml"
        | "tsvector"
        | "tsquery" => "string",

        "json" | "jsonb" => "any",
        "array" => "unknown[]",

        // Fallback: use unknown
        _ => "unknown",
    }
}

/// Query `information_schema.columns` for the given tables and return
/// column info grouped by schema-qualified table name.
pub(crate) async fn query_columns(
    client: &tokio_postgres::Client,
    tables: &[String],
) -> Result<BTreeMap<String, Vec<ColumnInfo>>, TapError> {
    let mut result: BTreeMap<String, Vec<ColumnInfo>> = BTreeMap::new();

    for table in tables {
        // Parse schema.table format
        let (schema, table_name) = table.split_once('.').unwrap_or(("public", table));

        let rows = client
            .query(
                "SELECT column_name, data_type, is_nullable
                 FROM information_schema.columns
                 WHERE table_schema = $1 AND table_name = $2
                 ORDER BY ordinal_position",
                &[&schema, &table_name],
            )
            .await?;

        let columns: Vec<ColumnInfo> = rows
            .iter()
            .map(|row| ColumnInfo {
                column_name: row.get(0),
                data_type: row.get(1),
                is_nullable: row.get::<_, String>(2) == "YES",
            })
            .collect();

        result.insert(table.clone(), columns);
    }

    Ok(result)
}

/// Generate TypeScript type definitions for the given table schemas.
pub(crate) async fn generate_typescript_types(
    client: &tokio_postgres::Client,
    tables: &[String],
) -> Result<String, TapError> {
    let columns_by_table = query_columns(client, tables).await?;
    let mut output = String::new();

    output.push_str("// Auto-generated by `tap inspect`\n");
    output.push_str("// TypeScript type definitions for captured tables.\n\n");

    for (table, columns) in &columns_by_table {
        // Convert "schema.table" to "SchemaTable" for the type name
        let type_name = table
            .replace('.', "_")
            .split('_')
            .filter(|s| !s.is_empty())
            .map(|s| {
                let mut chars = s.chars();
                match chars.next() {
                    None => String::new(),
                    Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
                }
            })
            .collect::<String>();

        let _ = writeln!(output, "export interface {type_name} {{");

        for col in columns {
            let ts_type = pg_type_to_ts(&col.data_type);
            let optional = if col.is_nullable { "?" } else { "" };
            let _ = writeln!(
                output,
                "  {col_name}{optional}: {ts_type};",
                col_name = col.column_name
            );
        }

        output.push_str("}\n\n");
    }

    output.push_str("// ── CDC event types ──────────────────────────────────\n");
    output.push_str("export type Operation = \"c\" | \"u\" | \"d\" | \"r\";\n\n");
    output.push_str("export interface SourceMetadata {\n");
    output.push_str("  db: string;\n");
    output.push_str("  schema: string;\n");
    output.push_str("  table: string;\n");
    output.push_str("  lsn: string;\n");
    output.push_str("  txId: string;\n");
    output.push_str("  tsMs: number;\n");
    output.push_str("  snapshot?: boolean;\n");
    output.push_str("}\n\n");
    output.push_str("export interface ChangeEvent {\n");
    output.push_str("  op: Operation;\n");
    output.push_str("  before: Record<string, unknown> | null;\n");
    output.push_str("  after: Record<string, unknown> | null;\n");
    output.push_str("  source: SourceMetadata;\n");
    output.push_str("  tsMs: number;\n");
    output.push_str("  id: string;\n");
    output.push_str("}\n");

    Ok(output)
}

/// Generate a JSON schema representation of the table columns.
pub(crate) async fn generate_json_schema(
    client: &tokio_postgres::Client,
    tables: &[String],
) -> Result<serde_json::Value, TapError> {
    let columns_by_table = query_columns(client, tables).await?;
    let mut schemas = serde_json::Map::new();

    for (table, columns) in &columns_by_table {
        let mut properties = serde_json::Map::new();
        let mut required = Vec::new();

        for col in columns {
            let ts_type = pg_type_to_ts(&col.data_type);
            let prop_type = match ts_type {
                "number" => "number",
                "boolean" => "boolean",
                _ => "string",
            };

            let mut prop = serde_json::Map::new();
            prop.insert("type".into(), serde_json::Value::String(prop_type.into()));
            prop.insert(
                "description".into(),
                serde_json::Value::String(format!("Postgres type: {}", col.data_type)),
            );

            properties.insert(col.column_name.clone(), serde_json::Value::Object(prop));

            if !col.is_nullable {
                required.push(col.column_name.clone());
            }
        }

        let mut schema = serde_json::Map::new();
        schema.insert("type".into(), serde_json::Value::String("object".into()));
        schema.insert("title".into(), serde_json::Value::String(table.clone()));
        schema.insert("properties".into(), serde_json::Value::Object(properties));
        schema.insert(
            "required".into(),
            serde_json::Value::Array(
                required
                    .into_iter()
                    .map(serde_json::Value::String)
                    .collect(),
            ),
        );

        schemas.insert(table.clone(), serde_json::Value::Object(schema));
    }

    Ok(serde_json::Value::Object(schemas))
}

/// Run `tap inspect`.
pub async fn run(args: InspectArgs) -> Result<(), TapError> {
    let config = crate::config::load_config(&args.config)?;

    let (client, _handle) = connect_plain(&config.source).await?;

    // Determine which tables to inspect
    let tables = if config.source.tables.is_empty() {
        // List all tables from the publication
        let rows = client
            .query(
                "SELECT schemaname || '.' || tablename \
                 FROM pg_publication_tables \
                 WHERE pubname = $1 \
                 ORDER BY schemaname, tablename",
                &[&config.source.publication],
            )
            .await?;
        rows.iter()
            .map(|r| r.get::<_, String>(0))
            .collect::<Vec<_>>()
    } else {
        config.source.tables.clone()
    };

    if tables.is_empty() {
        return Err(TapError::Config(
            "No tables configured and no tables found in the publication".into(),
        ));
    }

    // Determine output path
    let default_output = if args.json {
        ".tap/types/schema.json".to_string()
    } else {
        ".tap/types/schema.d.ts".to_string()
    };
    let output_path = args.output.unwrap_or(default_output);

    // Generate output
    let output_content: String = if args.json {
        let schema = generate_json_schema(&client, &tables).await?;
        serde_json::to_string_pretty(&schema)
            .map_err(|e| TapError::Decode(format!("Failed to serialize JSON schema: {e}")))?
    } else {
        generate_typescript_types(&client, &tables).await?
    };

    // Write to file or stdout
    if output_path == "-" {
        println!("{output_content}");
    } else {
        let parent = std::path::Path::new(&output_path).parent();
        if let Some(p) = parent {
            if !p.as_os_str().is_empty() {
                std::fs::create_dir_all(p)?;
            }
        }
        std::fs::write(&output_path, &output_content)?;
        println!("✓ Wrote schema to {output_path}");
    }

    Ok(())
}

// Used in run() for plain-text Postgres connections.
use tap_core::postgres::connect_plain;
