//! Error types for Tap operations.
//!
//! Central `TapError` enum using `thiserror` for `Display` and `Error`
//! impls.  Use `?` with any of the covered error types to propagate
//! errors automatically via the generated `From` impls.

pub mod reconnect;

pub use reconnect::ReconnectConfig;

use thiserror::Error;

/// Unified error type for all Tap operations.
///
/// Each variant wraps a specific error domain and provides a human-readable
/// description via the `Display` trait (generated by `thiserror`).
///
/// # Examples
///
/// ```
/// use tap_core::error::TapError;
///
/// let err = TapError::Config("missing required field".into());
/// assert!(err.to_string().contains("missing required field"));
/// ```
#[derive(Debug, Error)]
pub enum TapError {
    /// Error from the Postgres wire protocol or replication connection.
    ///
    /// The inner error may include the connection string in its `Display`
    /// output on some variants (e.g., authentication failures).  Use
    /// [`TapError::PostgresConnectionRedacted`] at connect sites where
    /// the connection string may contain secrets.
    #[error("Postgres connection error: {0}")]
    PostgresConnection(#[from] tokio_postgres::Error),

    /// Postgres connection error with credentials redacted from the message.
    ///
    /// Used at connect sites where the `tokio_postgres::Error` display may
    /// include the connection string with password.  The inner string
    /// already has the password replaced with `<REDACTED>`.
    #[error("Postgres connection error: {0}")]
    PostgresConnectionRedacted(String),

    /// Error from the SQLite state-store backend.
    #[error("SQLite error: {0}")]
    Sqlite(#[from] rusqlite::Error),

    /// Configuration parsing or validation error.
    #[error("Configuration error: {0}")]
    Config(String),

    /// Error during SQLite schema migration (DDL execution or unknown version).
    #[error("Migration failed: {0}")]
    MigrationFailed(String),

    /// Error related to Postgres replication slot management.
    #[error("Replication slot error: {0}")]
    ReplicationSlot(String),

    /// Unexpected or corrupted data in the state store.
    #[error("State store corruption: {0}")]
    StateCorruption(String),

    /// Data decoding or format validation error (protocol violations, corrupt events).
    #[error("Data decode error: {0}")]
    Decode(String),

    /// Error from the MySQL wire protocol or binlog connection.
    ///
    /// The inner error may include the connection string in its `Display`
    /// output on some variants.  Use
    /// [`TapError::MySqlConnectionRedacted`] at connect sites where
    /// the connection string may contain secrets.
    #[error("MySQL connection error: {0}")]
    MySqlConnection(String),

    /// MySQL connection error with credentials redacted from the message.
    #[error("MySQL connection error: {0}")]
    MySqlConnectionRedacted(String),

    /// Standard I/O error (file reads, etc.).
    #[error("I/O error: {0}")]
    Io(#[from] std::io::Error),

    /// Error during snapshot operations.
    #[error("Snapshot error: {0}")]
    Snapshot(String),

    /// Error from the transform engine (wasmtime / QuickJS).
    #[error("Transform engine error: {0}")]
    Transform(String),
}
