//! Error types for Tap operations.
//!
//! Central `TapError` enum using `thiserror` for `Display` and `Error`
//! impls.  Use `?` with any of the covered error types to propagate
//! errors automatically via the generated `From` impls.

pub mod reconnect;

pub use reconnect::ReconnectConfig;

use thiserror::Error;

/// Unified error type for all Tap operations.
///
/// Each variant wraps a specific error domain and provides a human-readable
/// description via the `Display` trait (generated by `thiserror`).
///
/// # Examples
///
/// ```
/// use tap_core::error::TapError;
///
/// let err = TapError::Config("missing required field".into());
/// assert!(err.to_string().contains("missing required field"));
/// ```
#[derive(Debug, Error)]
pub enum TapError {
    /// Error from the Postgres wire protocol or replication connection.
    #[error("Postgres connection error: {0}")]
    PostgresConnection(#[from] tokio_postgres::Error),

    /// Error from the SQLite state-store backend.
    #[error("SQLite error: {0}")]
    Sqlite(#[from] rusqlite::Error),

    /// Configuration parsing or validation error.
    #[error("Configuration error: {0}")]
    Config(String),

    /// Error related to Postgres replication slot management.
    #[error("Replication slot error: {0}")]
    ReplicationSlot(String),

    /// Unexpected or corrupted data in the state store.
    #[error("State store corruption: {0}")]
    StateCorruption(String),

    /// Standard I/O error (file reads, etc.).
    #[error("I/O error: {0}")]
    Io(#[from] std::io::Error),

    /// Generic fall-through error for one-off messages.
    #[error("{0}")]
    Other(String),
}
